version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=dev
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
  gid:
    build:
      context: .
      dockerfile: Dockerfile
    image: gid
    container_name: gid_service
    hostname: gid
    # network_mode: host
    restart: unless-stopped
    command: ./main
    volumes:
      - ./logs:/root/gid/logs
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - mysql  
