// Code generated by yago. Make sure "github.com/hulklab/yago" is the first import statement.
package main // import "gid"

import (
	"github.com/hulklab/yago"

	_ "gid/app/route"
)

func main() {
	yago.NewCmd().RunCmd()
}
